# escape=`

FROM lacledeslan/gamesvr-srcds-csgo:linux

MAINTAINER Laclede's LAN <contact@lacledeslan.com>

ENV IMAGE="gamesvr-srcds-csgo-tourney:linux"

USER root

COPY ./dist /app/bin/

# CLEAN UP
RUN usermod -l CSGO.Tourney CSGO

USER CSGO.Tourney
	
WORKDIR /app/bin/
