# escape=`

FROM lacledeslan/gamesvr-csgo

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-csgo-tourney"

HEALTHCHECK NONE

COPY ./dist /app/csgo/

COPY ./dist.linux /app/csgo/

# UPDATE USERNAME
RUN usermod -l CSGOTourney CSGO

USER CSGOTourney

WORKDIR /app/
